vich_uploader:
    db_driver: orm
    twig: true            # set to false to disable twig integration
    form: true            # set to false to disable form integration

    mappings:
        missions_image:
            uri_prefix: '%app.path.missions_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.missions_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer