vich_uploader:
    db_driver: orm

    mappings:
        missions_image:
            uri_prefix: '%app.path.missions_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.missions_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer